import type {
  Contact,
  Customer,
  Supplier,
  Product,
  PricingRecord,
  Quotation,
  Order,
  Invoice,
  CustomerRequirement,
  Opportunity,
  Communication,
  Document,
  KycRecord,
  AiExtractionJob,
  Campaign,
  Expense,
  Payment,
  Delivery,
  User,
  Organisation,
  CrmSettings,
  SalesSettings,
  ProductSettings,
  TradeSettings,
} from "./domain";
import type { FxTable } from "./fx";

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();
/** Chat messages land minutes apart, not days — WhatsApp history looks wrong
 *  when every bubble in a conversation carries the same timestamp. */
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600000).toISOString();

/**
 * Twelve months of settled trading history, so the dashboard's trend, aging and
 * territory views have a real shape on first load rather than a single bar.
 * Deliberately uneven — a flat series would make the charts look synthetic and
 * would hide whether the period comparison is actually working.
 */
const tradingHistory: { customerId: string; currency: string; net: number; daysBack: number; collectDays: number }[] = [
  { customerId: "c1", currency: "GBP", net: 14800, daysBack: 350, collectDays: 26 },
  { customerId: "c4", currency: "EUR", net: 21400, daysBack: 320, collectDays: 31 },
  { customerId: "c1", currency: "GBP", net: 9600, daysBack: 285, collectDays: 19 },
  { customerId: "c2", currency: "EUR", net: 17250, daysBack: 250, collectDays: 44 },
  { customerId: "c4", currency: "EUR", net: 26900, daysBack: 215, collectDays: 28 },
  { customerId: "c1", currency: "GBP", net: 11300, daysBack: 180, collectDays: 22 },
  { customerId: "c2", currency: "EUR", net: 8400, daysBack: 150, collectDays: 35 },
  { customerId: "c4", currency: "EUR", net: 31200, daysBack: 120, collectDays: 24 },
  { customerId: "c1", currency: "GBP", net: 18700, daysBack: 95, collectDays: 30 },
  { customerId: "c2", currency: "EUR", net: 12950, daysBack: 70, collectDays: 21 },
];

const historicInvoices: Invoice[] = tradingHistory.map((h, index) => {
  const tax = h.currency === "GBP" ? Math.round(h.net * 0.2) : 0;
  return {
    id: `ih${index + 1}`,
    number: `INV-2025-${String(900 + index).padStart(4, "0")}`,
    customerId: h.customerId,
    status: "paid",
    lines: [
      {
        id: `ihl${index + 1}`,
        description: "Consolidated supply — see order",
        quantity: 1,
        unitPrice: h.net,
        currency: h.currency,
      },
    ],
    currency: h.currency,
    subtotal: h.net,
    tax,
    total: h.net + tax,
    issuedAt: daysAgo(h.daysBack),
    dueAt: daysAgo(h.daysBack - 30),
    paidAt: daysAgo(h.daysBack - h.collectDays),
    amountPaid: h.net + tax,
    createdAt: daysAgo(h.daysBack),
    updatedAt: daysAgo(h.daysBack - h.collectDays),
  } as Invoice;
});

export const seedData = {

  organisation: {
    legalName: "Renso Group Ltd",
    tradingName: "Renso Group",
    addressLine1: "843 Finchley Rd",
    city: "London",
    postcode: "NW11 8NA",
    country: "United Kingdom",
    vatNumber: "GB 123 4567 89",
    registrationNumber: "09876543",
    defaultCurrency: "GBP",
    phone: "+44 20 7946 0000",
    email: "info@rensogroup.com",
    website: "www.rensogroup.com",
  } as Organisation,

  users: [
    {
      id: "u1",
      name: "Roni Ornadel",
      email: "roni@rensogroup.com",
      role: "administrator",
      isActive: true,
      createdAt: daysAgo(400),
      lastLoginAt: now,
    },
    {
      id: "u2",
      name: "Commercial Lead",
      email: "commercial@rensogroup.com",
      role: "commercial",
      isActive: true,
      createdAt: daysAgo(300),
      lastLoginAt: daysAgo(1),
    },
    {
      id: "u3",
      name: "Finance",
      email: "finance@rensogroup.com",
      role: "finance",
      isActive: true,
      createdAt: daysAgo(250),
      lastLoginAt: daysAgo(3),
    },
  ] as User[],

  crmSettings: {
    leadSources: ["Referral", "Website", "Trade show", "Cold outreach", "Historical email scan"],
    customerSegments: ["Wholesale", "Retail", "Distributor", "End user", "Other"],
    salesTerritories: ["UK & Ireland", "Northern Europe", "Southern Europe", "Middle East", "Asia Pacific", "Americas"],
    requireKycForOnboarding: true,
    followUpReminderDays: 5,
    documentExpiryWarningDays: 45,
  } as CrmSettings,

  salesSettings: {
    quotationPrefix: "QT-2026-",
    quotationValidityDays: 30,
    orderPrefix: "SO-2026-",
    defaultPaymentTerms: "30 days",
    defaultTaxRatePct: 20,
    requireApprovalAboveAmount: 25000,
  } as SalesSettings,

  productSettings: {
    categories: ["General", "Electronics", "Components", "Packaging", "Raw materials"],
    units: ["unit", "kg", "box", "pallet", "roll", "litre"],
    defaultCurrency: "GBP",
    lowMarginThresholdPct: 15,
  } as ProductSettings,

  /**
   * Rate table. Entered by hand and dated, because that is the only honest
   * provenance a client-side build can claim (see `lib/fx.ts`). GBP is the
   * base: the company reports in sterling, files VAT in sterling, and banks
   * in sterling.
   *
   * The PLN rate is left deliberately old so the stale-rate warning has a real
   * case to render rather than a contrived one.
   */
  fx: {
    base: "GBP",
    rates: [
      { currency: "USD", perBase: 1.2640, asOf: daysAgo(2) },
      { currency: "EUR", perBase: 1.1720, asOf: daysAgo(2) },
      { currency: "NOK", perBase: 13.480, asOf: daysAgo(9) },
      { currency: "CNY", perBase: 9.0400, asOf: daysAgo(4) },
      { currency: "PLN", perBase: 5.0300, asOf: daysAgo(74) },
    ],
  } as FxTable,

  tradeSettings: {
    defaultDutyPct: 4.7,
    defaultInsurancePct: 0.35,
    defaultFreightTotal: 1850,
    freightCurrency: "GBP",
    targetMarginPct: 22,
    priceAlertThresholdPct: 5,
  } as TradeSettings,

  dismissedSignals: [] as string[],

  contacts: [
    {
      id: "ct1",
      firstName: "James",
      lastName: "Whitfield",
      email: "procurement@aethertrading.co.uk",
      phone: "+44 20 7946 0123",
      jobTitle: "Procurement Manager",
      isPrimary: true,
      customerId: "c1",
      createdAt: daysAgo(180),
      updatedAt: daysAgo(2),
    },
    {
      id: "ct2",
      firstName: "Ingrid",
      lastName: "Berg",
      email: "orders@nordiccomp.no",
      jobTitle: "Buyer",
      isPrimary: true,
      customerId: "c2",
      createdAt: daysAgo(120),
      updatedAt: daysAgo(5),
    },
    {
      id: "ct3",
      firstName: "Wei",
      lastName: "Chen",
      email: "sales@szprecision.cn",
      phone: "+86 755 8888 1234",
      jobTitle: "Export Sales",
      isPrimary: true,
      supplierId: "s1",
      createdAt: daysAgo(300),
      updatedAt: daysAgo(1),
    },
  ] as Contact[],

  customers: [
    {
      id: "c1",
      name: "Aether Trading Ltd",
      tradingName: "Aether",
      status: "active",
      segment: "wholesale",
      email: "procurement@aethertrading.co.uk",
      phone: "+44 20 7946 0123",
      city: "London",
      postcode: "EC2A 4BX",
      country: "United Kingdom",
      currency: "GBP",
      paymentTerms: "30 days from invoice",
      creditLimit: 60000,
      tags: ["priority", "electronics"],
      ownerId: "u2",
      territory: "UK & Ireland",
      kycStatus: "approved",
      relationshipScore: 92,
      totalRevenue: 184500,
      totalOrders: 14,
      lastOrderAt: daysAgo(12),
      createdAt: daysAgo(180),
      updatedAt: daysAgo(2),
    },
    {
      id: "c2",
      name: "Nordic Components AS",
      phone: "+47 922 40 118",
      status: "active",
      segment: "distributor",
      email: "orders@nordiccomp.no",
      city: "Oslo",
      country: "Norway",
      currency: "EUR",
      paymentTerms: "30 days from invoice",
      // Deliberately tight against a 65-day-old balance, so the credit control
      // module has a genuine "hold new orders" case on real seeded data.
      creditLimit: 15000,
      tags: ["nordic", "components"],
      ownerId: "u2",
      territory: "Northern Europe",
      kycStatus: "approved",
      relationshipScore: 78,
      totalRevenue: 97200,
      totalOrders: 8,
      lastOrderAt: daysAgo(28),
      createdAt: daysAgo(120),
      updatedAt: daysAgo(5),
    },
    {
      id: "c3",
      name: "Brightline Retail Group",
      phone: "+44 7700 900318",
      status: "onboarding",
      segment: "retail",
      email: "newaccounts@brightline.co.uk",
      city: "Manchester",
      country: "United Kingdom",
      currency: "GBP",
      tags: ["new"],
      kycStatus: "pending",
      relationshipScore: 45,
      totalRevenue: 0,
      totalOrders: 0,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(1),
    },
    {
      id: "c4",
      name: "MedTech Solutions GmbH",
      phone: "+49 89 4411 2200",
      status: "active",
      segment: "end_user",
      email: "supply@medtech.de",
      city: "Munich",
      country: "Germany",
      currency: "EUR",
      paymentTerms: "45 days from invoice",
      creditLimit: 90000,
      tags: ["medical", "priority"],
      ownerId: "u1",
      territory: "Northern Europe",
      kycStatus: "approved",
      relationshipScore: 88,
      totalRevenue: 213000,
      totalOrders: 11,
      lastOrderAt: daysAgo(9),
      createdAt: daysAgo(200),
      updatedAt: daysAgo(3),
    },
  ] as Customer[],

  suppliers: [
    {
      id: "s1",
      name: "Shenzhen Precision Parts Co.",
      status: "preferred",
      email: "sales@szprecision.cn",
      phone: "+86 755 8271 4409",
      city: "Shenzhen",
      country: "China",
      currency: "USD",
      tags: ["electronics", "fast"],
      relationshipScore: 91,
      totalSpend: 312000,
      totalOrders: 22,
      priceCompetitiveness: 94,
      deliveryPerformance: 88,
      lastOfferAt: daysAgo(3),
      createdAt: daysAgo(300),
      updatedAt: daysAgo(1),
    },
    {
      id: "s2",
      name: "EuroMetal Industries",
      status: "active",
      email: "export@eurometal.pl",
      phone: "+48 32 601 4477",
      city: "Katowice",
      country: "Poland",
      currency: "EUR",
      tags: ["metals", "eu"],
      relationshipScore: 82,
      totalSpend: 145000,
      totalOrders: 9,
      priceCompetitiveness: 79,
      deliveryPerformance: 95,
      lastOfferAt: daysAgo(8),
      createdAt: daysAgo(250),
      updatedAt: daysAgo(4),
    },
    {
      id: "s3",
      name: "Pacific Polymers Inc.",
      status: "active",
      email: "quotes@pacificpoly.com",
      city: "Singapore",
      country: "Singapore",
      currency: "USD",
      tags: ["polymers"],
      relationshipScore: 74,
      totalSpend: 89000,
      totalOrders: 6,
      priceCompetitiveness: 85,
      deliveryPerformance: 81,
      lastOfferAt: daysAgo(15),
      createdAt: daysAgo(190),
      updatedAt: daysAgo(10),
    },
    {
      id: "s4",
      name: "Guangzhou CircuitTech Ltd",
      status: "active",
      email: "sales@gzcircuittech.cn",
      city: "Guangzhou",
      country: "China",
      currency: "USD",
      tags: ["electronics"],
      relationshipScore: 61,
      totalSpend: 54000,
      totalOrders: 4,
      priceCompetitiveness: 58,
      deliveryPerformance: 72,
      lastOfferAt: daysAgo(4),
      createdAt: daysAgo(90),
      updatedAt: daysAgo(4),
    },
  ] as Supplier[],

  products: [
    {
      id: "p1",
      sku: "PCB-FR4-001",
      name: "FR4 PCB Board 1.6mm",
      category: "Electronics",
      unit: "pcs",
      packaging: "100/box",
      purchasePrice: 2.15,
      sellingPrice: 3.40,
      currency: "USD",
      supplierIds: ["s1", "s4"],
      tags: ["pcb"],
      isActive: true,
      createdAt: daysAgo(100),
      updatedAt: daysAgo(5),
    },
    {
      id: "p2",
      sku: "ALU-6061-T6",
      name: "Aluminium 6061-T6 Bar 25mm",
      category: "Metals",
      unit: "m",
      packaging: "3m lengths",
      purchasePrice: 8.90,
      sellingPrice: 14.50,
      currency: "EUR",
      supplierIds: ["s2"],
      tags: ["aluminium"],
      isActive: true,
      createdAt: daysAgo(90),
      updatedAt: daysAgo(12),
    },
    {
      id: "p3",
      sku: "ABS-NAT-5KG",
      name: "ABS Natural Resin 5kg",
      category: "Polymers",
      unit: "bag",
      packaging: "5kg",
      purchasePrice: 22.00,
      sellingPrice: 34.00,
      currency: "USD",
      supplierIds: ["s3"],
      tags: ["resin"],
      isActive: true,
      createdAt: daysAgo(80),
      updatedAt: daysAgo(7),
    },
  ] as Product[],

  pricingRecords: [
    {
      id: "pr_client_example",
      productName: "Industrial widget (client example)",
      supplierName: "Demo Supplier Co.",
      quantity: 500,
      unitPrice: 42,
      currency: "USD",
      deliveryInfo: "delivery in 3 weeks",
      source: "email",
      sourceRef: "msg-client-example",
      status: "pending_review",
      extractedAt: daysAgo(0),
      originalText: "We can offer 500 units at $42 each, delivery in 3 weeks",
      createdAt: daysAgo(0),
      updatedAt: daysAgo(0),
    },

    {
      id: "pr1",
      productId: "p1",
      productName: "FR4 PCB Board 1.6mm",
      supplierId: "s1",
      supplierName: "Shenzhen Precision Parts Co.",
      quantity: 5000,
      unitPrice: 1.98,
      currency: "USD",
      deliveryInfo: "FOB Shenzhen, 3 weeks",
      commercialTerms: "30% deposit, balance against B/L",
      source: "email",
      sourceRef: "msg-2025-02-12-001",
      status: "approved",
      extractedAt: daysAgo(2),
      approvedAt: daysAgo(1),
      originalText:
        "We can offer 5000 units of FR4 1.6mm at $1.98 each, delivery in 3 weeks FOB Shenzhen. Terms 30% deposit.",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: "pr1b",
      productId: "p1",
      productName: "FR4 PCB Board 1.6mm",
      supplierId: "s4",
      supplierName: "Guangzhou CircuitTech Ltd",
      quantity: 5000,
      unitPrice: 2.15,
      currency: "USD",
      deliveryInfo: "FOB Guangzhou, 4 weeks",
      commercialTerms: "50% deposit, balance against B/L",
      source: "email",
      sourceRef: "msg-2026-01-08-014",
      status: "approved",
      extractedAt: daysAgo(4),
      approvedAt: daysAgo(3),
      originalText:
        "Quotation: 5000 pcs FR4 1.6mm board, $2.15/pc, FOB Guangzhou, lead time 4 weeks, 50% deposit required.",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(3),
    },
    {
      id: "pr2",
      productId: "p2",
      productName: "Aluminium 6061-T6 Bar 25mm",
      supplierId: "s2",
      supplierName: "EuroMetal Industries",
      quantity: 2000,
      unitPrice: 8.45,
      currency: "EUR",
      deliveryInfo: "DDP London, 10 days",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(8),
      approvedAt: daysAgo(7),
      originalText: "Offer: 2000m of 6061-T6 25mm at €8.45/m, DDP London, 10 working days.",
      createdAt: daysAgo(8),
      updatedAt: daysAgo(7),
    },
    /* ------------------------------------------------------------------ *
     * Price history.
     *
     * Every approved offer is a dated observation, so these are what the
     * price index actually reads. Three shapes on purpose: FR4 drifting down
     * as two Chinese suppliers compete, aluminium climbing on LME, and ABS
     * flat — a product where the honest answer is "no movement", which the
     * curve has to be able to say as clearly as it says "up 14%".
     * ------------------------------------------------------------------ */
    {
      id: "prh1",
      productId: "p1",
      productName: "FR4 PCB Board 1.6mm",
      supplierId: "s1",
      supplierName: "Shenzhen Precision Parts Co.",
      quantity: 5000,
      unitPrice: 2.24,
      currency: "USD",
      deliveryInfo: "FOB Shenzhen, 3 weeks",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(84),
      approvedAt: daysAgo(83),
      originalText: "FR4 1.6mm, 5000 pcs at $2.24 each FOB Shenzhen.",
      createdAt: daysAgo(84),
      updatedAt: daysAgo(83),
    },
    {
      id: "prh2",
      productId: "p1",
      productName: "FR4 PCB Board 1.6mm",
      supplierId: "s4",
      supplierName: "Guangzhou CircuitTech Ltd",
      quantity: 5000,
      unitPrice: 2.36,
      currency: "USD",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(62),
      approvedAt: daysAgo(61),
      originalText: "5000 pcs FR4 1.6mm at $2.36/pc, FOB Guangzhou.",
      createdAt: daysAgo(62),
      updatedAt: daysAgo(61),
    },
    {
      id: "prh3",
      productId: "p1",
      productName: "FR4 PCB Board 1.6mm",
      supplierId: "s1",
      supplierName: "Shenzhen Precision Parts Co.",
      quantity: 10000,
      unitPrice: 2.09,
      currency: "USD",
      deliveryInfo: "FOB Shenzhen, 3 weeks",
      source: "whatsapp",
      status: "approved",
      extractedAt: daysAgo(34),
      approvedAt: daysAgo(33),
      originalText: "For 10,000 pcs we can do $2.09 each, same terms.",
      createdAt: daysAgo(34),
      updatedAt: daysAgo(33),
    },
    {
      id: "prh4",
      productId: "p2",
      productName: "Aluminium 6061-T6 Bar 25mm",
      supplierId: "s2",
      supplierName: "EuroMetal Industries",
      quantity: 2000,
      unitPrice: 7.60,
      currency: "EUR",
      deliveryInfo: "DDP London, 10 days",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(76),
      approvedAt: daysAgo(75),
      originalText: "2000m of 6061-T6 25mm at EUR 7.60/m DDP London.",
      createdAt: daysAgo(76),
      updatedAt: daysAgo(75),
    },
    {
      id: "prh5",
      productId: "p2",
      productName: "Aluminium 6061-T6 Bar 25mm",
      supplierId: "s2",
      supplierName: "EuroMetal Industries",
      quantity: 1000,
      unitPrice: 7.95,
      currency: "EUR",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(45),
      approvedAt: daysAgo(44),
      originalText: "Revised: EUR 7.95/m for 1000m, LME has moved.",
      createdAt: daysAgo(45),
      updatedAt: daysAgo(44),
    },
    {
      id: "prh6",
      productId: "p2",
      productName: "Aluminium 6061-T6 Bar 25mm",
      supplierId: "s3",
      supplierName: "Pacific Polymers Inc.",
      quantity: 500,
      unitPrice: 9.10,
      currency: "USD",
      deliveryInfo: "CIF Southampton",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(26),
      approvedAt: daysAgo(25),
      originalText: "We can also supply 6061-T6: $9.10/m CIF Southampton, 500m minimum.",
      createdAt: daysAgo(26),
      updatedAt: daysAgo(25),
    },
    {
      id: "prh7",
      productId: "p3",
      productName: "ABS Natural Resin 5kg",
      supplierId: "s3",
      supplierName: "Pacific Polymers Inc.",
      quantity: 500,
      unitPrice: 19.60,
      currency: "USD",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(58),
      approvedAt: daysAgo(57),
      originalText: "500 bags ABS natural at $19.60 each CIF Southampton.",
      createdAt: daysAgo(58),
      updatedAt: daysAgo(57),
    },
    {
      id: "prh8",
      productId: "p3",
      productName: "ABS Natural Resin 5kg",
      supplierId: "s3",
      supplierName: "Pacific Polymers Inc.",
      quantity: 1000,
      unitPrice: 19.75,
      currency: "USD",
      source: "email",
      status: "approved",
      extractedAt: daysAgo(22),
      approvedAt: daysAgo(21),
      originalText: "1000 bags at $19.75 each, 6 week lead time.",
      createdAt: daysAgo(22),
      updatedAt: daysAgo(21),
    },
    {
      id: "pr3",
      productName: "ABS Natural Resin 5kg",
      productId: "p3",
      supplierId: "s3",
      supplierName: "Pacific Polymers Inc.",
      quantity: 500,
      unitPrice: 19.80,
      currency: "USD",
      deliveryInfo: "CIF Southampton, 4 weeks",
      source: "whatsapp",
      status: "pending_review",
      extractedAt: daysAgo(1),
      originalText: "We can offer 500 bags at $19.80 each, CIF Southampton, delivery 4 weeks.",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ] as PricingRecord[],

  quotations: [
    {
      id: "q1",
      number: "QT-2026-0042",
      customerId: "c1",
      status: "sent",
      lines: [
        {
          id: "ql1",
          productId: "p1",
          description: "FR4 PCB Board 1.6mm",
          quantity: 2000,
          unitPrice: 3.25,
          currency: "GBP",
        },
      ],
      currency: "GBP",
      subtotal: 6500,
      tax: 1300,
      total: 7800,
      validUntil: daysAgo(-14),
      sentAt: daysAgo(5),
      followUpAt: daysAgo(-2),
      createdAt: daysAgo(6),
      updatedAt: daysAgo(5),
    },
  ] as Quotation[],

  orders: [
    {
      id: "o1",
      number: "SO-2026-0018",
      customerId: "c4",
      status: "confirmed",
      lines: [
        {
          id: "ol1",
          productId: "p2",
          description: "Aluminium 6061-T6 Bar 25mm",
          quantity: 500,
          unitPrice: 14.50,
          currency: "EUR",
        },
      ],
      currency: "EUR",
      subtotal: 7250,
      tax: 0,
      total: 7250,
      incoterms: "DAP Munich",
      deliveryAddress: "MedTech Solutions GmbH, Landsberger Str. 302, 80687 München",
      customerReference: "PO-MT-4471",
      createdAt: daysAgo(10),
      updatedAt: daysAgo(9),
    },
    {
      id: "o2",
      number: "SO-2026-0017",
      customerId: "c1",
      quotationId: "q1",
      status: "in_progress",
      lines: [
        {
          id: "ol2",
          productId: "p1",
          description: "FR4 PCB Board 1.6mm",
          quantity: 10000,
          unitPrice: 2.15,
          currency: "GBP",
        },
        {
          id: "ol3",
          description: "Tooling and setup",
          quantity: 1,
          unitPrice: 850,
          currency: "GBP",
        },
      ],
      currency: "GBP",
      subtotal: 22350,
      tax: 4470,
      total: 26820,
      deliveryDate: daysAgo(-12),
      incoterms: "FCA Shenzhen",
      deliveryAddress: "Aether Trading Ltd, Unit 4 Hackney Wick, London E9 5EN",
      customerReference: "AET-PO-20261",
      notes: "Split shipment agreed — 4,000 air freight, balance by sea.",
      createdAt: daysAgo(22),
      updatedAt: daysAgo(3),
    },
    {
      id: "o3",
      number: "SO-2026-0015",
      customerId: "c2",
      status: "delivered",
      lines: [
        {
          id: "ol4",
          productId: "p3",
          description: "ABS Natural Resin 5kg",
          quantity: 400,
          unitPrice: 21.5,
          currency: "EUR",
        },
      ],
      currency: "EUR",
      subtotal: 8600,
      tax: 0,
      total: 8600,
      deliveryDate: daysAgo(31),
      incoterms: "CIF Oslo",
      deliveryAddress: "Nordic Components AS, Kabelgata 8, 0580 Oslo",
      createdAt: daysAgo(58),
      updatedAt: daysAgo(30),
    },
    {
      id: "o4",
      number: "SO-2026-0019",
      customerId: "c3",
      status: "draft",
      lines: [
        {
          id: "ol5",
          productId: "p1",
          description: "FR4 PCB Board 1.6mm — sample run",
          quantity: 250,
          unitPrice: 2.4,
          currency: "GBP",
        },
      ],
      currency: "GBP",
      subtotal: 600,
      tax: 120,
      total: 720,
      notes: "Held until KYC is approved.",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  ] as Order[],

  /**
   * Despatches. o2 is deliberately part-shipped so the fulfilment maths, the
   * progress bar and the "cannot over-despatch" guard all have a real case to
   * render rather than an all-or-nothing one.
   */
  deliveries: [
    {
      id: "dl1",
      orderId: "o2",
      reference: "DN-SO-2026-0017-01",
      quantities: { ol2: 4000, ol3: 1 },
      carrier: "DHL Air",
      trackingRef: "JJD0099887766",
      despatchedAt: daysAgo(6),
      deliveredAt: daysAgo(3),
      incoterms: "FCA Shenzhen",
      destination: "Aether Trading Ltd, London E9 5EN",
      notes: "First air shipment — 4,000 boards plus tooling.",
      createdAt: daysAgo(6),
    },
    {
      id: "dl2",
      orderId: "o3",
      reference: "DN-SO-2026-0015-01",
      quantities: { ol4: 400 },
      carrier: "Bring Cargo",
      trackingRef: "BRG-55120934",
      despatchedAt: daysAgo(35),
      deliveredAt: daysAgo(31),
      incoterms: "CIF Oslo",
      destination: "Nordic Components AS, Oslo",
      createdAt: daysAgo(35),
    },
  ] as Delivery[],

  invoices: [
    {
      id: "i1",
      number: "INV-2026-0091",
      customerId: "c1",
      status: "paid",
      lines: [
        {
          id: "il1",
          description: "FR4 PCB Board 1.6mm — 3000 pcs",
          quantity: 3000,
          unitPrice: 3.40,
          currency: "GBP",
        },
      ],
      currency: "GBP",
      subtotal: 10200,
      tax: 2040,
      total: 12240,
      issuedAt: daysAgo(40),
      paidAt: daysAgo(28),
      amountPaid: 12240,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(28),
    },
    {
      id: "i2",
      number: "INV-2026-0104",
      customerId: "c4",
      status: "issued",
      lines: [
        {
          id: "il2",
          description: "Aluminium 6061-T6 Bar 25mm — 500m",
          quantity: 500,
          unitPrice: 14.50,
          currency: "EUR",
        },
      ],
      currency: "EUR",
      subtotal: 7250,
      tax: 0,
      total: 7250,
      issuedAt: daysAgo(8),
      dueAt: daysAgo(-22),
      createdAt: daysAgo(8),
      updatedAt: daysAgo(8),
    },
    {
      // Deliberately overdue so the receivables aging view is not all "Current".
      id: "i3",
      number: "INV-2026-0088",
      customerId: "c2",
      status: "partial",
      lines: [
        {
          id: "il3",
          description: "Nitrile Gloves Blue L — 240 boxes",
          quantity: 240,
          unitPrice: 41.0,
          currency: "EUR",
        },
      ],
      currency: "EUR",
      subtotal: 9840,
      tax: 0,
      total: 9840,
      amountPaid: 4000,
      issuedAt: daysAgo(95),
      dueAt: daysAgo(65),
      createdAt: daysAgo(95),
      updatedAt: daysAgo(30),
    },
    ...historicInvoices,
  ] as Invoice[],

  requirements: [
    {
      id: "r1",
      customerId: "c1",
      productName: "FR4 PCB Board 1.6mm",
      productId: "p1",
      quantity: 10000,
      specification: "HASL finish, green solder mask",
      destination: "London warehouse",
      timing: "Within 5 weeks",
      status: "matching",
      matchedSupplierIds: ["s1"],
      commercialRequirements: "30 days from invoice, DAP London",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
    {
      id: "r2",
      customerId: "c4",
      productName: "Aluminium 6061-T6 Bar 25mm",
      productId: "p2",
      quantity: 800,
      specification: "Mill certs required, 3m lengths",
      destination: "Munich",
      timing: "Q4 call-off",
      status: "quoted",
      matchedSupplierIds: ["s2"],
      commercialRequirements: "Prices held 90 days",
      createdAt: daysAgo(18),
      updatedAt: daysAgo(11),
    },
    {
      id: "r3",
      customerId: "c2",
      productName: "ABS Natural Resin 5kg",
      productId: "p3",
      quantity: 1200,
      specification: "Natural, unpigmented, food-contact grade",
      destination: "Oslo",
      timing: "Within 8 weeks",
      status: "open",
      matchedSupplierIds: [],
      notes: "Pacific Polymers offer is still pending review — nothing approved to quote from.",
      createdAt: daysAgo(6),
      updatedAt: daysAgo(6),
    },
    {
      id: "r4",
      customerId: "c3",
      productName: "FR4 PCB Board 0.8mm",
      quantity: 2500,
      specification: "ENIG finish, black solder mask",
      destination: "Manchester",
      timing: "Sample first, production Q1",
      status: "open",
      matchedSupplierIds: [],
      notes: "Held behind KYC approval.",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ] as CustomerRequirement[],

  opportunities: [
    {
      id: "opp1",
      customerId: "c1",
      requirementId: "r1",
      productId: "p1",
      supplierId: "s1",
      title: "Aether — 10k FR4 boards",
      stage: "quotation",
      value: 32500,
      currency: "GBP",
      nextAction: "Send revised quotation",
      nextActionDue: daysAgo(-1),
      createdAt: daysAgo(4),
      updatedAt: daysAgo(1),
    },
  ] as Opportunity[],

  communications: [
    /* ---------------------------------------------------------------- */
    /* Mailbox. Every message is bound to the customer/supplier it came  */
    /* from and, where it exists, the commercial record it is about —    */
    /* that binding is what lets the reading pane show live quotation,   */
    /* order and invoice context instead of a wall of loose text.        */
    /* ---------------------------------------------------------------- */
    {
      id: "cm1",
      threadId: "th-fr4-offer",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "Offer — FR4 1.6mm, 5,000 pcs",
      body: `Dear Roni,

Thank you for your enquiry. We can offer 5,000 units of FR4 1.6mm at $1.98 each, delivery in 3 weeks FOB Shenzhen. Terms 30% deposit, balance against copy B/L.

The price holds for 14 days. We have the material in stock and can start production on receipt of the deposit.

Please let me know if you would like us to reserve the quantity.

Best regards,
Wei Zhang
Sales Manager — Shenzhen Precision Parts Co.`,
      from: "sales@szprecision.cn",
      fromName: "Wei Zhang",
      to: "trading@rensogroup.com",
      supplierId: "s1",
      productId: "p1",
      pricingRecordId: "pr1",
      isReceived: true,
      isRead: false,
      isStarred: true,
      attachments: [
        { id: "att1", name: "SZP-Offer-FR4-1.6mm.pdf", mimeType: "application/pdf", size: 184320 },
        { id: "att2", name: "FR4-datasheet-rev4.pdf", mimeType: "application/pdf", size: 962560 },
      ],
      extracted: true,
      occurredAt: daysAgo(2),
      createdAt: daysAgo(2),
    },
    {
      id: "cm2",
      threadId: "th-qt0042",
      channel: "email",
      direction: "outbound",
      folder: "sent",
      subject: "Quotation QT-2026-0042 — FR4 PCB Board 1.6mm",
      body: `Dear James,

Please find attached our quotation QT-2026-0042 for 2,000 pcs of FR4 PCB Board 1.6mm at GBP 3.25 each.

The quotation is valid for 14 days. Lead time is 3–4 weeks ex-works, and we can improve on that if the order is placed this week.

Kind regards,
Roni Ornadel
Renso Group`,
      from: "trading@rensogroup.com",
      fromName: "Roni Ornadel",
      to: "procurement@aethertrading.co.uk",
      customerId: "c1",
      quotationId: "q1",
      productId: "p1",
      isReceived: false,
      isRead: true,
      attachments: [
        { id: "att3", name: "QT-2026-0042.pdf", mimeType: "application/pdf", size: 128000, documentId: "d2" },
      ],
      occurredAt: daysAgo(5),
      createdAt: daysAgo(5),
    },
    {
      id: "cm3",
      threadId: "th-qt0042",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "RE: Quotation QT-2026-0042 — FR4 PCB Board 1.6mm",
      body: `Hi Roni,

Thanks for this. The specification is right and the lead time works for us.

We are comparing against one other supplier on price. If you can move on the unit rate for the 2,000 pcs we can place the order this week — otherwise we will likely split the volume.

Can you come back to me by Friday?

James Whitfield
Procurement — Aether Trading Ltd`,
      from: "procurement@aethertrading.co.uk",
      fromName: "James Whitfield",
      to: "trading@rensogroup.com",
      customerId: "c1",
      contactId: "ct1",
      quotationId: "q1",
      isReceived: true,
      isRead: false,
      isFlagged: true,
      occurredAt: daysAgo(3),
      createdAt: daysAgo(3),
    },
    {
      id: "cm4",
      threadId: "th-inv0104",
      channel: "email",
      direction: "outbound",
      folder: "sent",
      subject: "Invoice INV-2026-0104 — Aluminium 6061-T6 Bar",
      body: `Dear Sir/Madam,

Please find attached invoice INV-2026-0104 covering order SO-2026-0018, 500m of Aluminium 6061-T6 Bar 25mm, EUR 7,250.00.

Payment is due within 30 days of the invoice date. Our bank details are on the invoice.

Kind regards,
Renso Group — Accounts`,
      from: "accounts@rensogroup.com",
      fromName: "Renso Group Accounts",
      to: "einkauf@medtech-solutions.de",
      customerId: "c4",
      invoiceId: "i2",
      orderId: "o1",
      isReceived: false,
      isRead: true,
      attachments: [
        { id: "att4", name: "INV-2026-0104.pdf", mimeType: "application/pdf", size: 96000 },
      ],
      occurredAt: daysAgo(8),
      createdAt: daysAgo(8),
    },
    {
      id: "cm5",
      threadId: "th-inv0088",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "INV-2026-0088 — part payment sent",
      body: `Hello,

We have released EUR 4,000 against invoice INV-2026-0088 today. The balance of EUR 5,840 is held pending the credit note we discussed for the two damaged cartons.

Could you confirm the credit note reference so we can clear the remainder in this payment run?

Regards,
Astrid Lindqvist
Finance — Nordic Components AS`,
      from: "finance@nordiccomponents.no",
      fromName: "Astrid Lindqvist",
      to: "accounts@rensogroup.com",
      customerId: "c2",
      invoiceId: "i3",
      isReceived: true,
      isRead: true,
      isFlagged: true,
      occurredAt: daysAgo(30),
      createdAt: daysAgo(30),
    },
    {
      id: "cm6",
      threadId: "th-alu-price",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "Aluminium 6061-T6 — updated Q3 pricing",
      body: `Roni,

LME has moved and we are re-issuing our bar pricing with effect from the 1st.

Aluminium 6061-T6 Bar 25mm: EUR 11.40/m for 500m+, EUR 10.95/m for 2,000m+. Delivery 12–15 working days ex Duisburg. Payment 45 days as agreed.

Full list attached. Prices firm for 30 days.

Klaus Brenner
EuroMetal Industries`,
      from: "k.brenner@eurometal.de",
      fromName: "Klaus Brenner",
      to: "trading@rensogroup.com",
      supplierId: "s2",
      productId: "p2",
      isReceived: true,
      isRead: false,
      attachments: [
        { id: "att5", name: "EuroMetal-Pricelist-Q3.xlsx", mimeType: "application/vnd.ms-excel", size: 45056 },
      ],
      occurredAt: daysAgo(1),
      createdAt: daysAgo(1),
    },
    {
      id: "cm7",
      threadId: "th-kyc-brightline",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "KYC pack — Brightline Retail Group",
      body: `Good afternoon,

Attached is our completed onboarding pack: certificate of incorporation, VAT registration, two directors' ID and a recent utility bill for the registered address.

Let me know if anything further is needed to open the account.

Priya Raman
Brightline Retail Group`,
      from: "p.raman@brightlineretail.com",
      fromName: "Priya Raman",
      to: "compliance@rensogroup.com",
      customerId: "c3",
      isReceived: true,
      isRead: true,
      attachments: [
        { id: "att6", name: "Brightline — KYC pack.zip", mimeType: "application/zip", size: 3145728, documentId: "d3" },
      ],
      occurredAt: daysAgo(12),
      createdAt: daysAgo(12),
    },
    {
      id: "cm8",
      threadId: "th-abs-enquiry",
      channel: "email",
      direction: "inbound",
      folder: "inbox",
      subject: "Enquiry — ABS natural resin, recurring monthly",
      body: `Hi,

We are looking for a regular monthly supply of ABS natural resin, 5kg bags, roughly 4 tonnes per month starting next quarter. Delivered Rotterdam.

Can you indicate a price and confirm you can hold that volume? Happy to sign an annual agreement if the number is right.

Thanks,
James Whitfield
Aether Trading Ltd`,
      from: "procurement@aethertrading.co.uk",
      fromName: "James Whitfield",
      to: "trading@rensogroup.com",
      customerId: "c1",
      contactId: "ct1",
      productId: "p3",
      isReceived: true,
      isRead: false,
      occurredAt: daysAgo(4),
      createdAt: daysAgo(4),
    },
    {
      id: "cm9",
      threadId: "th-pacific-lead",
      channel: "email",
      direction: "inbound",
      folder: "archive",
      subject: "Pacific Polymers — capacity update",
      body: `Roni,

Just to flag that our Q3 extrusion capacity is now committed. We can still take ABS orders but lead time goes to 6 weeks rather than 4 until October.

No change to pricing.

Mei Tanaka
Pacific Polymers Inc.`,
      from: "m.tanaka@pacificpolymers.com",
      fromName: "Mei Tanaka",
      to: "trading@rensogroup.com",
      supplierId: "s3",
      productId: "p3",
      isReceived: true,
      isRead: true,
      occurredAt: daysAgo(21),
      createdAt: daysAgo(21),
    },
    {
      id: "cm10",
      threadId: "th-qt0042",
      channel: "email",
      direction: "outbound",
      folder: "drafts",
      subject: "RE: Quotation QT-2026-0042 — revised pricing",
      body: `Hi James,

Thanks for coming back to me. On the 2,000 pcs I can do GBP 3.12 each if we can confirm this week —`,
      from: "trading@rensogroup.com",
      fromName: "Roni Ornadel",
      to: "procurement@aethertrading.co.uk",
      customerId: "c1",
      quotationId: "q1",
      isReceived: false,
      isRead: true,
      occurredAt: daysAgo(1),
      createdAt: daysAgo(1),
    },
    /* WhatsApp — same records, different presentation. Written as real
       conversations (several turns, minutes apart, both directions) because a
       chat client seeded with three orphan messages looks broken in exactly
       the way a chat client shouldn't. */
    {
      id: "cm11", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Shenzhen Precision",
      body: "Roni — copper is moving again this week. Wanted to give you warning before the revision goes out.",
      from: "+86 755 8271 4409", fromName: "Wei Zhang", to: "+44 7700 900418",
      supplierId: "s1", productId: "p1",
      isReceived: true, isRead: true,
      occurredAt: hoursAgo(50), createdAt: hoursAgo(50),
    },
    {
      id: "cm14", channel: "whatsapp", direction: "outbound", folder: "sent",
      subject: "Shenzhen Precision",
      body: "Appreciated Wei. How long can you hold the current number?",
      from: "+44 7700 900418", fromName: "Roni Ornadel", to: "+86 755 8271 4409",
      supplierId: "s1", productId: "p1",
      isReceived: false, isRead: true,
      occurredAt: hoursAgo(49), createdAt: hoursAgo(49),
    },
    {
      id: "cm15", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Shenzhen Precision",
      body: "We can offer 10,000 pcs at 1.98 USD each, delivery in 3 weeks. That holds until Friday, after that the copper surcharge goes on.",
      from: "+86 755 8271 4409", fromName: "Wei Zhang", to: "+44 7700 900418",
      supplierId: "s1", productId: "p1",
      isReceived: true, isRead: false,
      occurredAt: hoursAgo(26), createdAt: hoursAgo(26),
    },
    {
      id: "cm12", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Aether Trading",
      body: "Morning — any movement on that FR4 number? Board meeting Thursday and I'd like to put it forward.",
      from: "+44 7700 900112", fromName: "James Whitfield", to: "+44 7700 900418",
      customerId: "c1", quotationId: "q1", orderId: "o2",
      isReceived: true, isRead: true, isFlagged: true,
      occurredAt: hoursAgo(46), createdAt: hoursAgo(46),
    },
    {
      id: "cm13", channel: "whatsapp", direction: "outbound", folder: "sent",
      subject: "Aether Trading",
      body: "Morning James — working on it now, I'll have a revised number with you before end of day today.",
      from: "+44 7700 900418", fromName: "Roni Ornadel", to: "+44 7700 900112",
      customerId: "c1", quotationId: "q1",
      isReceived: false, isRead: true,
      occurredAt: hoursAgo(45), createdAt: hoursAgo(45),
    },
    {
      id: "cm16", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Aether Trading",
      body: "Perfect. Also — the first 4,000 landed this morning, all counted in. Balance still on the water?",
      from: "+44 7700 900112", fromName: "James Whitfield", to: "+44 7700 900418",
      customerId: "c1", orderId: "o2",
      isReceived: true, isRead: false,
      occurredAt: hoursAgo(5), createdAt: hoursAgo(5),
    },
    {
      id: "cm17", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "EuroMetal Industries",
      body: "Roni, price revision goes out Monday. 6061-T6 bar moves to 8.95 EUR. Anything you want to lock in before then, tell me today.",
      from: "+48 32 601 4477", fromName: "Marta Kowalska", to: "+44 7700 900418",
      supplierId: "s2", productId: "p2",
      isReceived: true, isRead: false,
      occurredAt: hoursAgo(9), createdAt: hoursAgo(9),
    },
    {
      id: "cm18", channel: "whatsapp", direction: "outbound", folder: "sent",
      subject: "Nordic Components",
      body: "Hi Ingrid — DN-SO-2026-0015-01 shows as delivered on our side. Could you confirm so we can close the order out?",
      from: "+44 7700 900418", fromName: "Roni Ornadel", to: "+47 922 40 118",
      customerId: "c2", orderId: "o3",
      isReceived: false, isRead: false,
      occurredAt: hoursAgo(30), createdAt: hoursAgo(30),
    },
    {
      id: "cm19", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Nordic Components",
      body: "Confirmed, all 400 received in good order. Invoice can follow.",
      from: "+47 922 40 118", fromName: "Ingrid Solberg", to: "+44 7700 900418",
      customerId: "c2", orderId: "o3",
      isReceived: true, isRead: true,
      occurredAt: hoursAgo(28), createdAt: hoursAgo(28),
    },
    /* ------------------------------------------------------------------ *
     * Logged calls and older correspondence.
     *
     * Requirement 8 asks for communication activity including calls. Calls are
     * a channel on the same model rather than a separate record type, so they
     * appear in the account timeline, the activity heatmap and the response
     * measurement without a second code path. Dates are spread across the
     * quarter so the heatmap shows texture — and gaps — rather than one block.
     * ------------------------------------------------------------------ */
    {
      id: "cm21", channel: "call", direction: "outbound", folder: "sent",
      subject: "Call — Aether, FR4 pricing",
      body: "Called James to walk through the revised FR4 number. He will take it to Thursday's board meeting. 12 minutes.",
      fromName: "Roni Ornadel",
      customerId: "c1", contactId: "ct1", quotationId: "q1",
      isReceived: false, isRead: true,
      occurredAt: daysAgo(2), createdAt: daysAgo(2),
    },
    {
      id: "cm22", channel: "call", direction: "inbound", folder: "inbox",
      subject: "Call — Nordic, INV-2026-0088 balance",
      body: "Astrid called about the held balance on INV-2026-0088. Wants the credit note reference before the next payment run. 8 minutes.",
      fromName: "Astrid Lindqvist",
      customerId: "c2", invoiceId: "i3",
      isReceived: true, isRead: true,
      occurredAt: daysAgo(9), createdAt: daysAgo(9),
    },
    {
      id: "cm23", channel: "call", direction: "outbound", folder: "sent",
      subject: "Call — EuroMetal, Q3 revision",
      body: "Spoke to Klaus about the aluminium revision. Holding current pricing on anything confirmed this week. 6 minutes.",
      fromName: "Roni Ornadel",
      supplierId: "s2", productId: "p2",
      isReceived: false, isRead: true,
      occurredAt: daysAgo(16), createdAt: daysAgo(16),
    },
    {
      id: "cm24", channel: "email", direction: "outbound", folder: "sent",
      subject: "MedTech — Q3 aluminium call-off schedule",
      body: `Dear Anke,

Confirming the call-off schedule against the framework: 500m in July, 800m in September, priced per the agreement.

Kind regards,
Roni Ornadel
Renso Group`,
      from: "trading@rensogroup.com", fromName: "Roni Ornadel",
      to: "supply@medtech.de",
      customerId: "c4", productId: "p2",
      isReceived: false, isRead: true,
      occurredAt: daysAgo(23), createdAt: daysAgo(23),
    },
    {
      id: "cm25", channel: "email", direction: "inbound", folder: "archive",
      subject: "RE: MedTech — Q3 aluminium call-off schedule",
      body: `Roni,

Schedule confirmed on our side. Please send the July release against PO-MT-4471.

Anke Reuter
MedTech Solutions GmbH`,
      from: "a.reuter@medtech-solutions.de", fromName: "Anke Reuter",
      to: "trading@rensogroup.com",
      customerId: "c4",
      isReceived: true, isRead: true,
      occurredAt: daysAgo(22), createdAt: daysAgo(22),
    },
    {
      id: "cm26", channel: "email", direction: "inbound", folder: "archive",
      subject: "Shenzhen Precision — Chinese New Year shutdown dates",
      body: `Roni,

Factory closes for two weeks from the 9th. Anything you need before then should be confirmed in the next fortnight.

Wei Zhang
Shenzhen Precision Parts Co.`,
      from: "sales@szprecision.cn", fromName: "Wei Zhang",
      to: "trading@rensogroup.com",
      supplierId: "s1",
      isReceived: true, isRead: true,
      occurredAt: daysAgo(41), createdAt: daysAgo(41),
    },
    {
      id: "cm27", channel: "email", direction: "outbound", folder: "sent",
      subject: "Renso Group — introduction and capability",
      body: `Dear Priya,

Following your enquiry, a short introduction to what we do and the categories we cover. Happy to quote against a specific requirement whenever you have one.

Kind regards,
Roni Ornadel`,
      from: "trading@rensogroup.com", fromName: "Roni Ornadel",
      to: "newaccounts@brightline.co.uk",
      customerId: "c3",
      isReceived: false, isRead: true,
      occurredAt: daysAgo(33), createdAt: daysAgo(33),
    },
    {
      id: "cm20", channel: "whatsapp", direction: "inbound", folder: "inbox",
      subject: "Brightline Retail",
      body: "Hi Roni — we've uploaded the KYC pack. Anything else you need from us before the sample order can move?",
      from: "+44 7700 900318", fromName: "Priya Raman", to: "+44 7700 900418",
      customerId: "c3", orderId: "o4",
      isReceived: true, isRead: false,
      occurredAt: hoursAgo(20), createdAt: hoursAgo(20),
    },
  ] as Communication[],


  /**
   * Costs and cash. Purchases are deliberately booked against the same orders
   * and suppliers the sales side uses, so gross profit in Accounting is a
   * measured figure rather than an overhead assumption.
   */
  expenses: [
    {
      id: "ex1",
      date: daysAgo(12),
      description: "FR4 laminate — 3,000 pcs against INV-2026-0091",
      category: "purchases",
      supplierId: "s1",
      supplierName: "Shenzhen Precision Parts Co.",
      net: 5940,
      vat: 1188,
      currency: "GBP",
      reference: "SZP-2026-118",
      isPaid: true,
      paidAt: daysAgo(5),
      createdAt: daysAgo(12),
    },
    {
      id: "ex2",
      date: daysAgo(11),
      description: "Aluminium 6061-T6 bar — 500m against SO-2026-0018",
      category: "purchases",
      supplierId: "s2",
      supplierName: "EuroMetal Industries",
      orderId: "o1",
      net: 5700,
      vat: 0,
      currency: "EUR",
      reference: "EM-88214",
      isPaid: false,
      createdAt: daysAgo(11),
    },
    {
      id: "ex3",
      date: daysAgo(9),
      description: "Sea freight & import duty — Shenzhen to Felixstowe",
      category: "freight_duty",
      net: 1840,
      vat: 368,
      currency: "GBP",
      reference: "FRT-4471",
      isPaid: true,
      paidAt: daysAgo(4),
      createdAt: daysAgo(9),
    },
    {
      id: "ex4",
      date: daysAgo(20),
      description: "Office rent — 843 Finchley Rd, monthly",
      category: "premises",
      net: 2400,
      vat: 480,
      currency: "GBP",
      isPaid: true,
      paidAt: daysAgo(20),
      createdAt: daysAgo(20),
    },
    {
      id: "ex5",
      date: daysAgo(18),
      description: "Accountancy — quarterly bookkeeping and VAT",
      category: "professional_fees",
      net: 950,
      vat: 190,
      currency: "GBP",
      isPaid: false,
      createdAt: daysAgo(18),
    },
    {
      id: "ex6",
      date: daysAgo(15),
      description: "Salaries — monthly payroll",
      category: "salaries",
      net: 11400,
      vat: 0,
      currency: "GBP",
      isPaid: true,
      paidAt: daysAgo(15),
      createdAt: daysAgo(15),
    },
    {
      id: "ex7",
      date: daysAgo(7),
      description: "CRM, email and cloud hosting",
      category: "software",
      net: 340,
      vat: 68,
      currency: "GBP",
      isPaid: true,
      paidAt: daysAgo(7),
      createdAt: daysAgo(7),
    },
    {
      id: "ex8",
      date: daysAgo(30),
      description: "Trade show stand — Hannover",
      category: "marketing",
      net: 3200,
      vat: 640,
      currency: "EUR",
      isPaid: false,
      createdAt: daysAgo(30),
    },
  ] as Expense[],

  payments: [
    {
      id: "pay1",
      direction: "in",
      invoiceId: "i1",
      customerId: "c1",
      amount: 12240,
      currency: "GBP",
      method: "bank_transfer",
      reference: "FT26041900812",
      paidAt: daysAgo(28),
      createdBy: "u1",
      createdAt: daysAgo(28),
    },
    {
      id: "pay2",
      direction: "in",
      invoiceId: "i3",
      customerId: "c2",
      amount: 4000,
      currency: "EUR",
      method: "bank_transfer",
      reference: "NCAS-PR-3318",
      notes: "Part payment. Balance held pending credit note for damaged cartons.",
      paidAt: daysAgo(30),
      createdBy: "u3",
      createdAt: daysAgo(30),
    },
    {
      id: "pay3",
      direction: "out",
      expenseId: "ex1",
      supplierId: "s1",
      amount: 7128,
      currency: "GBP",
      method: "bank_transfer",
      reference: "BP-2026-0442",
      paidAt: daysAgo(5),
      createdBy: "u3",
      createdAt: daysAgo(5),
    },
    {
      id: "pay4",
      direction: "out",
      expenseId: "ex3",
      amount: 2208,
      currency: "GBP",
      method: "bank_transfer",
      reference: "BP-2026-0448",
      paidAt: daysAgo(4),
      createdBy: "u3",
      createdAt: daysAgo(4),
    },
  ] as Payment[],

  campaigns: [
    {
      id: "cp1",
      name: "Q3 product portfolio — active wholesale accounts",
      status: "sent",
      subject: "Renso Group — Q3 product portfolio and indicative pricing",
      preheader: "Updated FR4, aluminium and polymer pricing, valid to end of quarter.",
      templateBody: `Dear {{first_name}},

Please find our updated Q3 portfolio attached, covering FR4 laminates, 6061-T6 aluminium bar and ABS polymer.

Indicative pricing is held for 30 days. If there is a line you buy regularly that isn't shown, reply to this message and we will quote it directly.

Kind regards,
{{sender_name}}
Renso Group`,
      audience: { target: "customers", statuses: ["active"], segments: ["wholesale", "distributor"] },
      recipients: [],
      recipientCount: 3,
      sentCount: 3,
      openCount: 2,
      clickCount: 1,
      bounceCount: 0,
      attachPortfolio: true,
      sentAt: daysAgo(18),
      createdBy: "u1",
      createdAt: daysAgo(20),
      updatedAt: daysAgo(18),
    },
    {
      id: "cp2",
      name: "Dormant account re-engagement",
      status: "draft",
      subject: "Has your requirement changed?",
      preheader: "A quick note from Renso Group.",
      templateBody: `Dear {{first_name}},

It has been a while since we last quoted {{company}}. Our supplier base has widened considerably this year and on several lines we are materially cheaper than we were.

If it is useful, I can put together a short indicative list against the items you used to buy.

Kind regards,
{{sender_name}}`,
      audience: { target: "customers", statuses: ["active", "inactive"], minRecencyDays: 120 },
      recipients: [],
      recipientCount: 0,
      sentCount: 0,
      createdBy: "u1",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
  ] as Campaign[],

  documents: [
    {
      id: "d1",
      name: "Aether Trading — Framework Agreement.pdf",
      type: "contract",
      reference: "RG-FA-2025-014",
      customerId: "c1",
      source: "upload",
      issuedAt: daysAgo(90),
      expiresAt: daysAgo(-320),
      createdAt: daysAgo(90),
    },
    {
      id: "d2",
      name: "QT-2026-0042.pdf",
      type: "quotation",
      customerId: "c1",
      source: "system",
      createdAt: daysAgo(6),
    },
    {
      id: "d3",
      name: "Brightline — KYC pack.zip",
      type: "kyc",
      customerId: "c3",
      source: "onboarding",
      issuedAt: daysAgo(1),
      expiresAt: daysAgo(-30),
      createdAt: daysAgo(1),
    },
    {
      id: "d4",
      name: "Shenzhen Precision — ISO 9001 Certificate.pdf",
      type: "certificate",
      reference: "ISO-9001-CN-88421",
      supplierId: "s1",
      source: "email",
      issuedAt: daysAgo(400),
      expiresAt: daysAgo(-21),
      createdAt: daysAgo(45),
    },
    {
      id: "d5",
      name: "Shenzhen Precision — Product liability insurance.pdf",
      type: "certificate",
      reference: "PL-2025-77310",
      supplierId: "s1",
      source: "email",
      issuedAt: daysAgo(390),
      expiresAt: daysAgo(12),
      createdAt: daysAgo(390),
    },
    {
      id: "d6",
      name: "MedTech Solutions — Supply Agreement.pdf",
      type: "contract",
      reference: "RG-SA-2024-007",
      customerId: "c4",
      source: "upload",
      issuedAt: daysAgo(200),
      expiresAt: daysAgo(-160),
      createdAt: daysAgo(200),
    },
  ] as Document[],


  kycRecords: [
    {
      id: "k1",
      customerId: "c3",
      status: "submitted",
      sentAt: daysAgo(5),
      submittedAt: daysAgo(1),
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
    },
  ] as KycRecord[],

  extractionJobs: [
    {
      id: "ej1",
      source: "email",
      sourceRef: "msg-2025-02-12-001",
      originalContent:
        "We can offer 5000 units of FR4 1.6mm at $1.98 each, delivery in 3 weeks FOB Shenzhen. Terms 30% deposit.",
      status: "pending_review",
      extractedRecords: [],
      createdAt: daysAgo(2),
    },
  ] as AiExtractionJob[],
};
